### ISSUE TITLE
Vad ska vi göra?

### ISSUE THREAD

**Issue by s4wny** [Filip9719/RISK#1]
# Vad ska vi göra?

![Ide stadie](http://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-177935.jpg)
## Ideer / brainstorming:
- crawla webben, filter som säger vad som ska crawlas in (lite väl abstrakt?)
- wallhaven sida
- Polys labyrint (är ett logiskt spel)
- risk (spelet risk, multiplayer, javascript)

**Comment by drPytho** [comment]
Risk låter roligt :) Något man skulle vara motiverad att jobba med

**Comment by drPytho** [comment]
Då kan man göra det med webGL i halv 3D(kanske) eller canvas i 2D. Javascript med websockets för multiplayer

**Comment by s4wny** [comment]
aaa, btw skype kanske är bättre för att chatta ;)

**Comment by drPytho** [comment]
Visst, men "Issues" är till för diskussion.

**Comment by s4wny** [comment]
Vid årsmötet 2015 beslutade ledningen att Risk är awesome.
